version: '3.8'

services:
  prefect-worker:
    build: .
    environment:
      # Connect to host Prefect server
      - PREFECT_API_URL=http://host.docker.internal:4200/api
    volumes:
      # Optional: Mount for development
      - ./complete_workflow:/app/complete_workflow
    networks:
      - prefect-network
    restart: unless-stopped

networks:
  prefect-network:
    driver: bridge