"""
Example: Blockly-Generated Code Pattern for OT-2

This script demonstrates the Python code that would be generated by the Blockly
visual programming interface. The code mirrors the example shown in the
blockly_concept_demo.html visualization.

This example shows how custom Blockly blocks can generate Python code that
directly calls functions from OT2mqtt.py, maintaining a one-to-one correspondence
between visual blocks and executable code.

Note: This is a demonstration of the code generation pattern. To actually execute
this code, you would need:
1. An OT-2 robot connected and configured
2. The MQTT broker connection details
3. The required labware and pipettes loaded
"""

# The imports below would be generated by Blockly based on which blocks are used
# In a real implementation, these would come from the actual OT2mqtt.py module
# from OT2mqtt import mix_color, move_sensor_back, protocol


def example_blockly_generated_workflow():
    """
    This function demonstrates the workflow that would be generated by
    the Blockly blocks shown in blockly_concept_demo.html
    
    The visual workflow consists of:
    1. Home Robot block
    2. Repeat 3 times:
       a. Mix Color block (R=100, Y=50, B=75, well=A1)
       b. Move Sensor Back block (status=complete)
    """
    
    # Block: OT-2: Home Robot
    # This corresponds to the "🏠 OT-2: Home Robot" block in Blockly
    print("Step 1: Homing the OT-2 robot...")
    # protocol.home()
    
    # Block: Repeat 3 times
    # This corresponds to the "🔁 Repeat 3 times" control block in Blockly
    for count in range(3):
        print(f"\n=== Iteration {count + 1} ===")
        
        # Block: OT-2: Mix Color
        # This corresponds to the "🎨 OT-2: Mix Color" block in Blockly
        # Each parameter field in the block becomes a key in the payload
        payload = {
            "command": {
                "R": 100,      # Red (µL) input field
                "Y": 50,       # Yellow (µL) input field
                "B": 75,       # Blue (µL) input field
                "well": "A1"   # Well input field
            },
            "session_id": "session_001",      # Session ID input field
            "experiment_id": "exp_001"         # Experiment ID input field
        }
        print(f"  Mixing colors: R={payload['command']['R']}µL, "
              f"Y={payload['command']['Y']}µL, B={payload['command']['B']}µL "
              f"in well {payload['command']['well']}")
        # mix_color(payload)
        
        # Block: OT-2: Move Sensor Back
        # This corresponds to the "↩️ OT-2: Move Sensor Back" block in Blockly
        payload = {
            "command": {
                "sensor_status": "complete"    # Sensor Status input field
            },
            "session_id": "session_001",       # Session ID input field
            "experiment_id": "exp_001"         # Experiment ID input field
        }
        print(f"  Moving sensor back to charging position...")
        # move_sensor_back(payload)
    
    print("\n✓ Workflow completed successfully!")


def demonstrate_block_to_code_mapping():
    """
    Demonstrates how each Blockly block type maps to Python code
    """
    print("=" * 70)
    print("BLOCKLY BLOCK-TO-CODE MAPPING DEMONSTRATION")
    print("=" * 70)
    
    print("\n1. OT-2: Home Robot Block")
    print("   Visual: [🏠 OT-2: Home Robot]")
    print("   Python: protocol.home()")
    
    print("\n2. OT-2: Mix Color Block")
    print("   Visual: [🎨 OT-2: Mix Color]")
    print("           Red (µL): 100")
    print("           Yellow (µL): 50")
    print("           Blue (µL): 75")
    print("           Well: A1")
    print("           Session ID: session_001")
    print("           Experiment ID: exp_001")
    print("""   Python: payload = {
               "command": {
                   "R": 100,
                   "Y": 50,
                   "B": 75,
                   "well": "A1"
               },
               "session_id": "session_001",
               "experiment_id": "exp_001"
           }
           mix_color(payload)""")
    
    print("\n3. OT-2: Move Sensor Back Block")
    print("   Visual: [↩️ OT-2: Move Sensor Back]")
    print("           Sensor Status: complete")
    print("           Session ID: session_001")
    print("           Experiment ID: exp_001")
    print("""   Python: payload = {
               "command": {
                   "sensor_status": "complete"
               },
               "session_id": "session_001",
               "experiment_id": "exp_001"
           }
           move_sensor_back(payload)""")
    
    print("\n4. Repeat N times Block (Standard Blockly)")
    print("   Visual: [🔁 Repeat 3 times]")
    print("           [nested blocks...]")
    print("   Python: for count in range(3):")
    print("               # nested code...")
    
    print("\n" + "=" * 70)


def show_extensibility_example():
    """
    Demonstrates how additional OT2mqtt.py functions could be wrapped
    as custom Blockly blocks
    """
    print("\n" + "=" * 70)
    print("EXTENSIBILITY: Adding More Custom Blocks")
    print("=" * 70)
    
    print("\nThe OT2mqtt.py module contains other functions that could be")
    print("wrapped as Blockly blocks following the same pattern:\n")
    
    print("Existing Functions in OT2mqtt.py:")
    print("  • mix_color(payload) - Lines 87-142")
    print("    ✓ Already implemented as Blockly block")
    print("  • move_sensor_back(payload) - Lines 144-162")
    print("    ✓ Already implemented as Blockly block")
    print("  • handle_command(payload) - Lines 164-173")
    print("    → Could be wrapped as a dispatcher block")
    print("  • protocol.home() - Used throughout")
    print("    ✓ Already implemented as Blockly block")
    
    print("\nTo add a new custom block for any Python function:")
    print("1. Define the Blockly block (JavaScript)")
    print("2. Define the Python code generator (JavaScript)")
    print("3. Add to the toolbox XML")
    print("\nThe one-to-one mapping ensures predictable code generation!")
    print("=" * 70)


if __name__ == "__main__":
    print("\n" + "🧪 " * 20)
    print("BLOCKLY + OT-2 INTEGRATION DEMONSTRATION")
    print("Visual Programming → Python Code Generation")
    print("🧪 " * 20 + "\n")
    
    # Show the mapping between blocks and code
    demonstrate_block_to_code_mapping()
    
    # Run the example workflow
    print("\n" + "=" * 70)
    print("EXECUTING BLOCKLY-GENERATED WORKFLOW")
    print("=" * 70)
    example_blockly_generated_workflow()
    
    # Show how to extend with more blocks
    show_extensibility_example()
    
    print("\n📚 For more information:")
    print("   • Open scripts/blockly_concept_demo.html in a browser")
    print("   • Read scripts/BLOCKLY_README.md")
    print("   • Try the interactive demo in scripts/blockly_ot2_demo.html")
    print()
