name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    paths: [.github/workflows/copilot-setup-steps.yml]
  pull_request:
    paths: [.github/workflows/copilot-setup-steps.yml]

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PIP_TIMEOUT: 600
      PIP_RETRIES: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Ensures we check out the actual head branch on PRs
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Derive branch name
        id: branch
        shell: bash
        run: |
          BN="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          if [ -z "$BN" ]; then BN="$(git branch --show-current || true)"; fi
          echo "BRANCH_NAME=$BN" | tee -a "$GITHUB_ENV"
          echo "name=$BN" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install package and dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ax-platform prefect prefect-slack
          python -m pip install -e .
          # python -m pip install tox pre-commit
          # pre-commit run --all-files
          # npx mint-mcp add docs.prefect.io
          # pre-commit install

      - name: Install branch-specific dependencies
        if: ${{ env.BRANCH_NAME == 'copilot/fix-382' }}
        run: |
          python -m pip install "ax-platform<1" prefect prefect-slack
